# Generated by Django 5.0.6 on 2024-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="book_name",
            field=models.CharField(max_length=250, verbose_name="Book Name"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="category",
            field=models.CharField(max_length=250, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="customer_name",
            field=models.CharField(max_length=250, verbose_name="Customer Name"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantity"),
        ),
    ]
