# Generated by Django 5.0.6 on 2024-08-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_alter_salesinvoice_book_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="customer_name",
            field=models.CharField(max_length=10, verbose_name="Customer Name"),
        ),
    ]
