# Generated by Django 5.0.6 on 2024-09-03 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0007_salesinvoice_customer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesinvoice",
            name="category",
        ),
    ]
