# Generated by Django 4.2.13 on 2024-09-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegulationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_import_amount",
                    models.PositiveIntegerField(
                        default=150, help_text="Số lượng nhập tối thiểu."
                    ),
                ),
                (
                    "max_import_stock",
                    models.PositiveIntegerField(
                        default=300, help_text="Chỉ nhập kho khi số lượng dưới mức này."
                    ),
                ),
                (
                    "max_debt",
                    models.PositiveIntegerField(
                        default=300, help_text="Mức nợ tối đa."
                    ),
                ),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=300, help_text="Số lượng tồn kho tối thiểu."
                    ),
                ),
                (
                    "payment_bill_limit",
                    models.BooleanField(
                        default=False,
                        help_text="Hóa đơn thanh toán của khách hàng không được vượt quá mức nợ.",
                    ),
                ),
            ],
        ),
    ]
