# Generated by Django 4.2.13 on 2024-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulationsetting",
            name="max_debt",
            field=models.DecimalField(
                decimal_places=2,
                default=500000.0,
                help_text="Mức nợ tối đa.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="regulationsetting",
            name="max_import_stock",
            field=models.PositiveIntegerField(
                default=100, help_text="Chỉ nhập kho khi số lượng dưới mức này."
            ),
        ),
        migrations.AlterField(
            model_name="regulationsetting",
            name="min_import_amount",
            field=models.PositiveIntegerField(
                default=50, help_text="Số lượng nhập tối thiểu."
            ),
        ),
    ]
