# Generated by Django 5.0.6 on 2024-08-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipt", "0004_alter_receipt_receipt_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="id",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="receipt_id",
            field=models.CharField(
                max_length=10,
                primary_key=True,
                serialize=False,
                verbose_name="Receipt ID",
            ),
        ),
    ]
