# Generated by Django 5.0.6 on 2024-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipt", "0006_alter_receipt_paid_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="receipt_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Receipt ID"
            ),
        ),
    ]
