# Generated by Django 4.2.13 on 2024-08-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=10, unique=True)),
                ("book_name", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("cover", models.CharField(max_length=50)),
            ],
        ),
    ]
