# Generated by Django 4.2.13 on 2024-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_remove_importedbook_book_remove_importedbook_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
