# Generated by Django 4.2.13 on 2024-08-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0006_remove_book_categories_remove_book_id_book_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBookOrder",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("user_id", models.CharField(max_length=10)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_import_order.importbookorder",
                    ),
                ),
            ],
        ),
    ]
