# Generated by Django 4.2.13 on 2024-09-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "book_import_order",
            "0003_importbookorder_amount_importbookorder_author_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importbookorder",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="importbookorder",
            name="author",
        ),
        migrations.RemoveField(
            model_name="importbookorder",
            name="book_id",
        ),
        migrations.RemoveField(
            model_name="importbookorder",
            name="book_name",
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(blank=True, max_length=10, null=True)),
                ("book_name", models.CharField(blank=True, max_length=250, null=True)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="book_import_order.importbookorder",
                    ),
                ),
            ],
        ),
    ]
