# Generated by Django 4.2.13 on 2024-09-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_import_order", "0004_remove_importbookorder_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="amount",
            field=models.IntegerField(default=1),
        ),
    ]
