# Generated by Django 4.2.13 on 2024-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_debtreport_inventoryreport_delete_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtreport",
            name="month",
            field=models.DateField(verbose_name="Month"),
        ),
        migrations.AlterField(
            model_name="inventoryreport",
            name="month",
            field=models.DateField(verbose_name="Month"),
        ),
    ]
